name: Bump Version
on:
  push:
    branches:
      - main

jobs:
  install-and-bump-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Fetch code PR
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        shell: bash
        run: npm install